### ISSUE TITLE
how can I use it in android project?

### ISSUE THREAD

**Issue by eenie** [adibfara/WatchTower#3]
I use it as demo in my android project,
but it crash.
the log is :
`05-29 15:44:07.939 18167-18167/com.zx.ksfensi E/CrashReport: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/snakydesign/watchtower/interceptor/WatchTowerInterceptor;
        at com.zx.ksfensi.CoupleApp.onCreate(CoupleApp.java:45)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1016)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4794)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.access$1700(ActivityThread.java:169)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1495)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5581)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
`

and I import this lib is ：
`  implementation 'com.snakyapps.watchtower:core:1.0.0'
    implementation 'com.snakyapps.watchtower:interceptor-okhttp:1.0.0'`

use it in my okhttpclient：
` .addInterceptor(new WatchTowerInterceptor())`

**Comment by adibfara** [comment]
Are you the class names are not removed by proguard/dexguard? (is `minifyEnabled` set to false?)

**Comment by eenie** [comment]
yes, `minifyEnabled ` always is false,BTW my android project is write in java,not kotlin,Is it  influences？or where can I found a demo for android,
thank you again.

**Comment by eenie** [comment]
I clear my project,and it work now.
thank you again.

**Comment by PankajSavaliya** [comment]
Could you please put your Java syntax here? because My project is also in Java. I have enabled kotlin support in my current java project but didn't work (Syntext error).

**Comment by tanliner** [comment]
OkHttpClient client = new OkHttpClient.Builder().addInterceptor(new WatchTowerInterceptor()).build();
Retrofit retrofit = new Retrofit.Builder().client(client)

// start onCreate
WebWatchTowerObserver[] towers = new WebWatchTowerObserver[1];
towers[0] = new WebWatchTowerObserver(8085, 5003);
WatchTower.INSTANCE.start(towers, 10);

// shutdown onDestroy
WatchTower.INSTANCE.shutDown();
